name: ${project.name}
description: ${project.description}
author: Hadde
version: ${project.version}
main: ${project.groupId}.eldoutilities.core.${project.name}
website: ${project.url}
api-version: 1.16